piVersion: apps/v1
kind: Deployment
metadata:
  name: tds-invoice-api
  namespace: tds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tds-invoice-api
  template:
    metadata:
      labels:
        app: tds-invoice-api
    spec:
      containers:
      - name: tds-invoice-api
        image: citfodvcr.azurecr.io/tds-invoice-api:{$id}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: tfo-cm
        - secretRef:
            name: tfo-secret
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: tfo-dev-deployment

---
apiVersion: v1
kind: Service
metadata:
  name: tds-invoice-api
  namespace: tds
spec:
  #type: NodePort
  ports:
  - port: 80
  selector:
    app: tds-invoice-api